.\" statb - simple info output
.\" Copyright (C) 2021-2022 FearlessDoggo21
.\" see LICENCE file for licensing information
.TH STATB 1 statb\-VERSION
.SH NAME
statb \- simple info output
.SH SYNOPSIS
.SY statb
.YS
.SH DESCRIPTION
.BR statb (1)
is a utility to edit the
.I WM_NAME
property of the root
.BR xorg (1)
window.  This is what
.BR dwm (1)
and other simple window managers read to display a simple textual bar on
screen.  
.BR statb (1)
takes advantage of this to provide a modular method of adding different pieces
of useful information, such as audio volume, battery charge, and internet
connectivity.
.SH USAGE
.BR statb (1)
can be run by adding it into to your
.I .xinitrc
file.  It can alternatively be started while a window manager is already
running.
.SH CUSTOMISATION
.BR statb (1)
is customised by creating a custom
.I config.h
and (re)compiling the source code.  Source code modification to configure
.BR statb (1)
keeps it fast, secure, and simple.
.SH BUGS
.BR statb (1)
will sometimes crash when switching to another tty.
.PP
.BR statb (1)
seems to not work on some systems.  Similarities between these systems normally
include not having batteries (required for the battery module) and not using
ALSA for the main audio control.  If these modules are removed,
.BR statb (1)
should function normally.
.SH AUTHOR
Written by FearlessDoggo21.
.SH SEE ALSO
.BR dwm "(1), " xinit "(1), " xorg (1)
