.TH STATB 1 statb\-VERSION
.SH NAME
statb \- simple info bar
.SH SYNOPSIS
\fBstatb\fR
.SH DESCRIPTION
\fBstatb\fR is a simple info bar for window managers which output \fBWM_NAME\fR
as an info bar.  It supports audio with ALSA, memory, battery life, internet,
and datetime with a small label.
.SH USAGE
\fBstatb\fR can be run by adding it into to your \fB.xinitrc\fR file. It can
alternatively be started while a window manager is already running.
.SH CUSTOMISATION
\fBstatb\fR is customised by creating a custom config.h and (re)compiling the
source code.  This keeps it fast, secure, and simple.
.SH SEE ALSO
.BR dwm "(1), " xinit (1)
.SH BUGS
\fBstatb\fR will sometimes crash when switching to another tty.
.PP
Send all bug reports to https://github.com/fearlessdoggo21/statb/issues, and
all patches to https://github.com/fearlessdoggo21/statb/pulls.
