.TH STATB 1 statb\-VERSION
.SH NAME
statb \- simple info bar
.SH SYNOPSIS
.B statb
.SH DESCRIPTION
.B statb
is a simple info bar for window managers which output WM_NAME as an info bar. It supports audio with ALSA, memory, battery life, internet, and datetime as well as a small label.
.SH USAGE
.B statb
can be run by adding it into to your
.BR startx (1)
.B .xinitrc
file. It can alternatively be started from within an already running window manager.
.SH CUSTOMIZATION
.B statb
is customized by creating a custom config.h and (re)compiling the source code.
.SH SEE ALSO
.BR dwm (1)
.SH BUGS
Create a bug report for
.B statb
at [https://github.com/fearlessdoggo21/statb/issues].
